### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by timqian** [timqian/mathlab#1]
- [x] [`pointwise()`](http://www.timqian.com/mathlab/function/index.html#static-function-pointwise) Create a pointwise function
- [ ] [`all()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    All the components of x are true
- [ ] [`any()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    One or more of the components of x are true
- [ ] [`ccsDim()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Dimensions of sparse matrix
- [ ] [`ccsDot()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Sparse matrix-matrix product
- [ ] [`ccsFull()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Convert sparse to full
- [ ] [`ccsGather()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Gather entries of sparse matrix
- [ ] [`ccsGetBlock()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Get rows/columns of sparse matrix
- [ ] [`ccsLUP()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Compute LUP decomposition of sparse matrix
- [ ] [`ccsLUPSolve()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Solve Ax=b using LUP decomp
- [ ] [`ccsScatter()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Scatter entries of sparse matrix
- [ ] [`ccsSparse()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Convert from full to sparse
- [ ] [`ccsTSolve()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Solve upper/lower triangular system
- [ ] [`ccs<op>()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Supported ops include: add/div/mul/geq/etc...
- [ ] [`cLU()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Coordinate matrix LU decomposition
- [ ] [`cLUsolve()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   Coordinate matrix LU solve
- [ ] [`cdelsq()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Coordinate matrix Laplacian
- [ ] [`cdotMV()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Coordinate matrix-vector product
- [ ] [`cgrid()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Coordinate grid for cdelsq
- [x] [`det()`](http://www.timqian.com/mathlab/function/index.html#static-function-det) Determinant
- [ ] [`diveq()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Pointwise x/=y
- [ ] [`dopri()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Numerical integration of ODE using Dormand-Prince RK method. Returns an object Dopri.
- [ ] [`Dopri.at()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   Evaluate the ODE solution at a point
- [ ] [`dot()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Matrix-Matrix, Matrix-Vector and Vector-Matrix product
- [ ] [`eig()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Eigenvalues and eigenvectors
- [ ] [`epsilon()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    2.220446049250313e-16
- [ ] [`getBlock()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   Extract a block from a matrix
- [x] [`getDiag()`](http://www.timqian.com/mathlab/function/index.html#static-function-getDiag) Get the diagonal of a matrix
- [x] [`identity()`](http://www.timqian.com/mathlab/function/index.html#static-function-identity)   Identity matrix
- [ ] [`imageURL()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   Encode a matrix as an image URL
- [x] [`inv()`](http://www.timqian.com/mathlab/function/index.html#static-function-inv) Matrix inverse
- [ ] [`largeArray()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Don't prettyPrint Arrays larger than this
- [ ] [`LU()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Dense LU decomposition
- [ ] [`LUsolve()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Dense LU solve
- [ ] [`mapreduce()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Make a pointwise map-reduce function
- [ ] [`norm2()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Square root of the sum of the square of the entries of x
- [ ] [`norm2Squared()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   Sum of squares of entries of x
- [ ] [`norminf()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Largest modulus entry of x
- [ ] [`parseCSV()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   Parse a CSV file into an Array
- [ ] [`parseDate()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Pointwise parseDate(x)
- [ ] [`parseFloat()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Pointwise parseFloat(x)
- [ ] [`precision()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Number of digits to prettyPrint
- [ ] [`prettyPrint()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Pretty-prints x
- [ ] [`random()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Create an Array of random numbers
- [ ] [`rep()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Create an Array by duplicating values
- [ ] [`same()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   x and y are entrywise identical
- [ ] [`seedrandom()`](http://www.timqian.com/mathlab/function/index.html#static-function-) The seedrandom module
- [ ] [`setBlock()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   Set a block of a matrix
- [ ] [`solve()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Solve Ax=b
- [ ] [`solveLP()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Solve a linear programming problem
- [ ] [`solveQP()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Solve a quadratic programming problem
- [ ] [`spline()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Create a Spline object
- [ ] [`Spline.at()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Evaluate the Spline at a point
- [ ] [`Spline.diff()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Differentiate the Spline
- [ ] [`Spline.roots()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   Find all the roots of the Spline
- [ ] [`subeq()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Pointwise x-=y
- [ ] [`sum()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Sum all the entries of x
- [ ] [`svd()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Singular value decomposition
- [ ] [`t()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Create a tensor type T (may be complex-valued)
- [ ] [`T.<numericfun>()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Supported <numericfun> are: abs, add, cos, diag, div, dot, exp, getBlock, getDiag, inv, log, mul, neg, norm2, setBlock, sin, sub, transpose
- [ ] [`T.conj()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Pointwise complex conjugate
- [ ] [`T.fft()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Fast Fourier transform
- [ ] [`T.get()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Read an entry
- [ ] [`T.getRow()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   Get a row
- [ ] [`T.getRows()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Get a range of rows
- [ ] [`T.ifft()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Inverse FFT
- [ ] [`T.reciprocal()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   Pointwise 1/z
- [ ] [`T.set()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Set an entry
- [ ] [`T.setRow()`](http://www.timqian.com/mathlab/function/index.html#static-function-)   Set a row
- [ ] [`T.setRows()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Set a range of rows
- [ ] [`T.transjugate()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  The conjugate-transpose of a matrix
- [ ] [`tensor()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Tensor product ret[i][j] = x[i]*y[j]
- [ ] [`toCSV()`](http://www.timqian.com/mathlab/function/index.html#static-function-)  Make a CSV file
- [x] [`transpose()`](http://www.timqian.com/mathlab/function/index.html#static-function-transpose) Matrix transpose
- [ ] [`uncmin()`](http://www.timqian.com/mathlab/function/index.html#static-function-) Unconstrained optimization
- [ ] [`version()`](http://www.timqian.com/mathlab/function/index.html#static-function-)    Version string for the numeric library
#### Pointwise functions
- [x] [`clone()`](http://www.timqian.com/mathlab/function/index.html#static-function-clone) Deep copy of Array
- [x] [`abs()`](http://www.timqian.com/mathlab/function/index.html#static-function-abs) Absolute value
- [x] [`acos()`](http://www.timqian.com/mathlab/function/index.html#static-function-acos)   Arc-cosine
- [x] [`add()`](http://www.timqian.com/mathlab/function/index.html#static-function-add) Pointwise sum x+y
- [x] [`and()`](http://www.timqian.com/mathlab/function/index.html#static-function-and) Pointwise x && y
- [x] [`asin()`](http://www.timqian.com/mathlab/function/index.html#static-function-asin)   Arc-sine
- [x] [`atan()`](http://www.timqian.com/mathlab/function/index.html#static-function-atan)   Arc-tangeant
- [x] [`atan2()`](http://www.timqian.com/mathlab/function/index.html#static-function-atan2) Arc-tangeant (two parameters)
- [x] [`band()`](http://www.timqian.com/mathlab/function/index.html#static-function-band)   Pointwise x & y
- [x] [`bnot()`](http://www.timqian.com/mathlab/function/index.html#static-function-bnot)   Binary negation ~x
- [x] [`bor()`](http://www.timqian.com/mathlab/function/index.html#static-function-bor) Binary or x|y
- [x] [`bxor()`](http://www.timqian.com/mathlab/function/index.html#static-function-bxor)   Binary xor x^y
- [x] [`ceil()`](http://www.timqian.com/mathlab/function/index.html#static-function-ceil)   Pointwise Math.ceil(x)
- [x] [`cos()`](http://www.timqian.com/mathlab/function/index.html#static-function-cos) Pointwise Math.cos(x)
- [x] [`diag()`](http://www.timqian.com/mathlab/function/index.html#static-function-diag)   Create diagonal matrix
- [x] [`dim()`](http://www.timqian.com/mathlab/function/index.html#static-function-dim) Get Array dimensions
- [x] [`div()`](http://www.timqian.com/mathlab/function/index.html#static-function-div) Pointwise x/y
- [x] [`eq()`](http://www.timqian.com/mathlab/function/index.html#static-function-eq)   Pointwise comparison x === y
- [x] [`exp()`](http://www.timqian.com/mathlab/function/index.html#static-function-exp) Pointwise Math.exp(x)
- [x] [`floor()`](http://www.timqian.com/mathlab/function/index.html#static-function-floor) Poinwise Math.floor(x)
- [x] [`geq()`](http://www.timqian.com/mathlab/function/index.html#static-function-geq) Pointwise x>=y
- [x] [`gt()`](http://www.timqian.com/mathlab/function/index.html#static-function-gt)   Pointwise x>y
- [x] [`leq()`](http://www.timqian.com/mathlab/function/index.html#static-function-leq) Pointwise x<=y
- [x] [`linspace()`](http://www.timqian.com/mathlab/function/index.html#static-function-linspace)   Generate evenly spaced values
- [x] [`log()`](http://www.timqian.com/mathlab/function/index.html#static-function-log) Pointwise Math.log(x)
- [x] [`lshift()`](http://www.timqian.com/mathlab/function/index.html#static-function-lshift)   Pointwise x<<y
- [x] [`lt()`](http://www.timqian.com/mathlab/function/index.html#static-function-lt)   Pointwise x<y
- [x] [`mod()`](http://www.timqian.com/mathlab/function/index.html#static-function-mod) Pointwise x%y
- [x] [`mul()`](http://www.timqian.com/mathlab/function/index.html#static-function-mul) Pointwise x*y
- [x] [`neg()`](http://www.timqian.com/mathlab/function/index.html#static-function-neg) Pointwise -x
- [x] [`neq()`](http://www.timqian.com/mathlab/function/index.html#static-function-neq) Pointwise x!==y
- [x] [`not()`](http://www.timqian.com/mathlab/function/index.html#static-function-not) Pointwise logical negation !x
- [x] [`or()`](http://www.timqian.com/mathlab/function/index.html#static-function-or)   Pointwise logical or x||y
- [x] [`pow()`](http://www.timqian.com/mathlab/function/index.html#static-function-pow) Pointwise Math.pow(x)
- [x] [`round()`](http://www.timqian.com/mathlab/function/index.html#static-function-round) Pointwise Math.round(x)
- [x] [`rrshift()`](http://www.timqian.com/mathlab/function/index.html#static-function-rrshift) Pointwise x>>>y
- [x] [`rshift()`](http://www.timqian.com/mathlab/function/index.html#static-function-rshift)   Pointwise x>>y
- [x] [`rshifteq()`](http://www.timqian.com/mathlab/function/index.html#static-function-rshift) Pointwise x>>=y
- [x] [`sin()`](http://www.timqian.com/mathlab/function/index.html#static-function-sin) Pointwise Math.sin(x)
- [x] [`sqrt()`](http://www.timqian.com/mathlab/function/index.html#static-function-sqrt)   Pointwise Math.sqrt(x)
- [x] [`sub()`](http://www.timqian.com/mathlab/function/index.html#static-function-sub) Pointwise x-y
- [x] [`tan()`](http://www.timqian.com/mathlab/function/index.html#static-function-tan) Pointwise Math.tan(x)
- [x] [`xor()`](http://www.timqian.com/mathlab/function/index.html#static-function-xor) Pointwise x^y
